all:
  children:
    hosts:
      prox-node1:
        ansible_host: 192.168.1.30
      ca01.haas.ch:
        ansible_host: 192.168.1.40
      vpn01.haas.ch:
        ansible_host: 192.168.1.41
      rproxyext01.haas.ch:
        ansible_host: 192.168.1.42
